# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASEIMAGE
ARG REGISTRY
FROM $REGISTRY/windows-image-builder-helper:1.1 as helper
FROM $BASEIMAGE

COPY --from=helper /Windows/System32/vcruntime140.dll /Windows/System32/
# TODO(claudiub): add a different Apache version
COPY --from=helper /Users/ContainerAdministrator/AppData/Roaming/Apache24 /usr/local
COPY --from=helper /tools/php72 /tools/php72

COPY httpd.conf /usr/local/conf/httpd.conf
COPY index.html /usr/local/htdocs/index.html

# NOTE(claudiub): docker buildx sets the PATH env variable to a Linux-like PATH, which is not desirable.
ENV PATH="C:\Windows\system32;C:\Windows;C:\Program Files\PowerShell;C:\tools\php72\;C:\usr\local\bin\;"

USER ContainerAdministrator
EXPOSE 80
ENTRYPOINT ["C:/usr/local/bin/httpd.exe"]
