# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BASEIMAGE
FROM $BASEIMAGE

RUN mkdir C:\usr\local\ &\
    cd C:\usr\local &\
    curl -L "https://github.com/etcd-io/etcd/releases/download/v3.4.3/etcd-v3.4.3-windows-amd64.zip" -o etcd-windows-amd64.zip &\
    tar -xf etcd-windows-amd64.zip &\
    move etcd-v3.4.3-windows-amd64 bin &\
    del etcd-windows-amd64.zip

ENTRYPOINT ["/usr/local/bin/etcd.exe"]
